### ISSUE TITLE
Failing to write version file with setuptools_scm 8 

### ISSUE THREAD

**Issue by bnavigator** [scikit-build/scikit-build#1031]
scikit-build seemst to suffer from the same problem as https://github.com/scikit-build/scikit-build-core/pull/509.

The Slycot CI started to fail because of it: https://github.com/python-control/Slycot/actions/runs/6285374495/job/17067739674?pr=214

**Comment by bnavigator** [comment]
Hmm,seems my initial assumption that scikit-build is involved was wrong. Was being mislead through the scikit-build-core issue. Sorry for the noise.

https://github.com/pypa/setuptools_scm/issues/933

**Comment by henryiii** [comment]
This was fixed in setuptools-scm 8.0.3 (and scikit-build-core’s latest release too). But it should have only affected scikit-build-core.

**Comment by bnavigator** [comment]
It still happens with setuptools_scm 8.0.3 when `setup(use_scm_version=True)` is being used. I am not sure why I had to add it, but I think it was for a reason, when we started to use setuptools_scm >=6.3.

https://github.com/python-control/Slycot/pull/180
